### ISSUE TITLE
Add redirect from old resources to this page

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-overview#1]
- https://www.w3.org/WAI/ER/2011/eval/

**Comment by slhenry** [comment]
Actually https://www.w3.org/WAI/ER/2011/eval/ should not be redirected to https://www.w3.org/WAI/test-evaluate/ -- without consideration from Shadi (who I won't tag since it's not high priority).

That page has more info and different purpose. Maybe we'll want to make it as archive with pointer to other relevant page. Anyway, low priority.
